# Generated by Django 2.0.4 on 2018-05-09 10:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=200, unique=True)),
                ('previous_db_id', models.IntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True)),
                ('established', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2050)])),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='boards/')),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('salient_features', models.TextField(blank=True, null=True)),
                ('international', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='board_documents/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='program.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to='board_images/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=200, unique=True)),
                ('previous_db_id', models.IntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='councils/')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouncilDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to='council_documents/')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='program.Council')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='council_images/')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Council')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=200, unique=True)),
                ('previous_db_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=200, unique=True)),
                ('previous_db_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=200, unique=True)),
                ('previous_db_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('Pre-school', 'Pre-school'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Post Graduate Diploma', 'Post Graduate Diploma'), ('Master of Philosophy', 'Master of Philosophy'), ('TSLC', 'TSLC'), ('Chartered Accountancy (CA)', 'Chartered Accountancy (CA)'), ('Certificate/Diploma', 'Certificate/Diploma'), ('Doctorate', 'Doctorate')], max_length=100, null=True)),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('job_prospects', models.TextField(blank=True, null=True)),
                ('salient_features', models.TextField(blank=True, null=True)),
                ('curricular_structure', models.TextField(blank=True, null=True)),
                ('admission_criteria', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Board')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='programs', to='program.Discipline')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Faculty')),
                ('recognition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Council')),
                ('related_programs', models.ManyToManyField(blank=True, related_name='_program_related_programs_+', to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='faculties',
            field=models.ManyToManyField(blank=True, to='program.Faculty'),
        ),
    ]
