# Generated by Django 2.0.4 on 2018-04-10 16:02

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to='council_documents/')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Council')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to='council_images/')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Council')),
            ],
        ),
    ]
