# Generated by Django 2.0.4 on 2018-04-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_councildocument_councilimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddocument',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='program.Board'),
        ),
        migrations.AlterField(
            model_name='boarddocument',
            name='file',
            field=models.FileField(upload_to='board_documents/'),
        ),
        migrations.AlterField(
            model_name='boardimage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Board'),
        ),
        migrations.AlterField(
            model_name='councildocument',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='program.Council'),
        ),
        migrations.AlterField(
            model_name='councilimage',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='program.Council'),
        ),
        migrations.AlterField(
            model_name='councilimage',
            name='file',
            field=models.FileField(upload_to='council_images/'),
        ),
    ]
