# Generated by Django 2.0.4 on 2018-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20180410_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('Pre-school', 'Pre-school'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
