# Generated by Django 2.0.4 on 2018-04-10 13:42

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20180410_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='boards/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
    ]
