# Generated by Django 2.0.4 on 2018-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20180415_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
    ]
