# Generated by Django 2.0.4 on 2018-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20180508_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
