# Generated by Django 2.0.4 on 2018-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_faculty_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
