# Generated by Django 2.0.4 on 2018-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_board_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
