# Generated by Django 2.0.4 on 2018-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_board_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
