# Generated by Django 2.0.4 on 2018-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_discipline_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
