# Generated by Django 2.0.4 on 2018-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180508_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
