# Generated by Django 2.0.4 on 2018-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_council_previous_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
