# Generated by Django 2.0.4 on 2018-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_program_previous_db_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='curricular_stucture',
            new_name='curricular_structure',
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('Pre-school', 'Pre-school'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Post Graduate Diploma', 'Post Graduate Diploma'), ('Master of Philosophy', 'Master of Philosophy'), ('TSLC', 'TSLC'), ('Chartered Accountancy (CA)', 'Chartered Accountancy (CA)'), ('Certificate/Diploma', 'Certificate/Diploma'), ('Doctorate', 'Doctorate')], max_length=30),
        ),
    ]
