# Generated by Django 2.0.4 on 2018-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='awards',
            field=models.ManyToManyField(related_name='institutes', through='institute.InstituteAward', to='institute.Award'),
        ),
        migrations.AddField(
            model_name='institute',
            name='personnels',
            field=models.ManyToManyField(related_name='institutes', through='institute.InstitutePersonnel', to='institute.Personnel'),
        ),
        migrations.AddField(
            model_name='institute',
            name='programs',
            field=models.ManyToManyField(related_name='institutes', through='institute.InstituteProgram', to='program.Program'),
        ),
    ]
