# Generated by Django 2.0.4 on 2018-04-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20180410_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprogram',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_program', to='institute.Institute'),
        ),
        migrations.AlterField(
            model_name='instituteprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_program', to='program.Program'),
        ),
    ]
