# Generated by Django 2.0.4 on 2018-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20180410_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='ugc_accredition',
            field=models.BooleanField(default=False, verbose_name='UGC Accredition'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.'),
        ),
    ]
