# Generated by Django 2.0.4 on 2018-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20180509_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedocument',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instituteimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
