# Generated by Django 2.0.4 on 2018-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20180509_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
