# Generated by Django 2.0.4 on 2018-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20180410_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', unique=True),
        ),
    ]
