# Generated by Django 2.0.4 on 2018-04-14 14:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20180410_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='awards/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='cover_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='institute_covers/'),
        ),
        migrations.AddField(
            model_name='instituteaward',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='institute_awards/'),
        ),
    ]
