# Generated by Django 2.0.4 on 2018-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20180414_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Community', 'Community')], default='Private', max_length=20),
        ),
    ]
