# Generated by Django 2.0.4 on 2018-04-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_institute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprogram',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_programs', to='institute.Institute'),
        ),
        migrations.AlterField(
            model_name='instituteprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_programs', to='program.Program'),
        ),
    ]
