# Generated by Django 2.0.4 on 2018-04-30 11:08

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_auto_20180423_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='instituteimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='instituteimage',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='institute_images/', width_field='width'),
        ),
    ]
