# Generated by Django 2.0.4 on 2018-05-01 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
