# Generated by Django 2.0.4 on 2018-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_auto_20180515_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
