# Generated by Django 2.0.4 on 2018-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_auto_20180527_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='is_member',
        ),
        migrations.AddField(
            model_name='institute',
            name='membership',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard')], max_length=20),
        ),
    ]
