# Generated by Django 2.0.4 on 2018-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_scholarshipcategory_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
