# Generated by Django 2.0.4 on 2018-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0015_ranking_previous_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank for autofill.', max_length=100, unique=True),
        ),
    ]
