# Generated by Django 2.0.4 on 2018-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_award_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('community', 'Community')], default='Private', max_length=20),
        ),
    ]
