# Generated by Django 2.0.4 on 2018-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_auto_20180527_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
