# Generated by Django 2.0.4 on 2018-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_auto_20180509_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('community', 'Community')], default='Private', max_length=20, null=True),
        ),
    ]
