# Generated by Django 2.0.4 on 2018-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_auto_20180509_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
