# Generated by Django 2.0.4 on 2018-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_institute_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='previous_db_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
