# Generated by Django 2.0.4 on 2018-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_scholarship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
