# Generated by Django 2.0.4 on 2018-05-27 10:43

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_scholarship_previous_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
