# Generated by Django 2.0.4 on 2018-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0021_scholarship_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='institutes',
            field=models.ManyToManyField(blank=True, null=True, to='institute.Institute'),
        ),
    ]
