# Generated by Django 2.0.4 on 2018-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0021_rank_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprogram',
            name='fee',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
