# Generated by Django 2.0.4 on 2018-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0022_auto_20180527_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
