# Generated by Django 2.0.4 on 2018-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0023_rank_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='institutes',
            field=models.ManyToManyField(blank=True, to='institute.Institute'),
        ),
    ]
