# Generated by Django 2.0.4 on 2018-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0024_auto_20180527_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedocument',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
